## *Information Retrieval Final Project*
### Yazdan asadi
9517023104

Part 1: Building a system to retrieve and indexing the poems
#TODO: 1-Indexing(10point) 2-Retrieve and search for queries (15point)
       3-Personalize Analyzer(10 point)

# Data Cleaning

In [6]:
#preprocess and make a csv file to query on it
from __future__ import unicode_literals
import os,re
import nltk
import csv
import pandas as pd
import numpy as np
from pathlib import Path
path = "/home/yazdan/Documents/IR Project/PersianPoemsData/Final Poems"

In [7]:
from hazm import *

In [8]:
def poems_to_csv(path):
    p_title = []
    p_title2 = []
    p_author2 = []
    p_body = []
    docs_id = 1
    file_count = 0
    df = pd.read_csv('first.csv',header = None)    
    for (dir_path,dir_name,file_names) in os.walk(path):
        file_count = len(file_names)
        #file = open('first.csv', 'w+', newline ='')
        #with file:     
            #write = csv.writer(file) 
            #write.writerows(p_author2)
            #write.writerows(p_title)
        for the_file in file_names:
            p = Path(dir_path).parent
            p_author =list(p.parts)[7:]
            author = [p_author]
            p_author2.append(author)
            with open(dir_path + '/' + the_file, 'r',encoding="utf-8") as my_file:
                lines = my_file.readlines()
                title = str(lines[1])
                body = lines[5:-2]
                changed_title = title.replace("\section*",'')
                changed_title = changed_title.replace("\n",'')
                p_title.append(changed_title)
               
                p_body.append(body)
                
            
    return  p_author2, p_title ,p_body

In [9]:
p_author2, p_title ,p_body = poems_to_csv(path)
print(len(p_author2))
print(len(p_title))
print(len(p_body))

7881
7881
7881


In [10]:
def to_csv(author, title, body):
    csv_file = []
    for i in range(len(author)):
        csv_file.append([author[i][0][0], title[i], body[i]])
        #print(author[i])
    return csv_file

In [11]:
res = [''.join(ele) for ele in p_body] 

In [15]:
csv_list = to_csv(p_author2, p_title ,res)

In [16]:
df = pd.DataFrame(csv_list,columns=['Author Name','Title of Poem','Poem Body'])

In [17]:
df.head(500)

Author Name                                      Title of Poem  \
0       khayyam        {رباعی شماره ۱۴۳: قومی متفکرند اندر ره دین}   
1       khayyam     {رباعی شماره ۱۵۹: از کوزه‌گری کوزه خریدم باری}   
2       khayyam   {رباعی شماره ۱۴: این بحر وجود آمده بیرون ز نهفت}   
3       khayyam        {رباعی شماره ۹۴: هم دانه امید به خرمن ماند}   
4       khayyam      {رباعی شماره ۲: چون عهده نمی‌شود کسی فردا را}   
..          ...                                                ...   
495     moulavi    {غزل شماره ۱۵۴۲: چنان مستم چنان مستم من این دم}   
496     moulavi  {غزل شماره ۲۳۲۶: ای بر سر بازاری دستار چنان کرده}   
497     moulavi         {غزل شماره ۱۲۵: گفتی که گزیده‌ای تو بر ما}   
498     moulavi         {غزل شماره ۲۵۰: هین که منم بر در در برگشا}   
499     moulavi  {غزل شماره ۲۸۸۹: ای که تو چشمه حیوان و بهار چمنی}   

                                             Poem Body  
0    قومی متفکرند اندر ره دین\n&&\nقومی به گمان فتا...  
1    از کوزه‌گری کوزه خریدم باری\n&&\nآن کوزه سخن گ...  
2    این بحر وجود آمده بیرون ز نهفت\n&&\nکس نیست که...  
3    هم دانه امید به خرمن ماند\n&&\nهم باغ و سرای ب...  
4    چون عهده نمی‌شود کسی فردا را\n&&\nحالی خوش دار...  
..                                                 ...  
495  چنان مستم چنان مستم من این دم\n&&\nکه حوا را ب...  
496  ای بر سر بازاری دستار چنان کرده\n&&\nرو با دگر...  
497  گفتی که گزیده‌ای تو بر ما\n&&\nهرگز نبدست این ...  
498  هین که منم بر در در برگشا\n&&\nبستن در نیست نش...  
499  ای که تو چشمه حیوان و بهار چمنی\n&&\nچو منی تو...  

[500 rows x 3 columns]

# Normalizer

In [18]:
norm = Normalizer()

In [19]:
df_ii = df

In [20]:
df_ii['Nomralized Poem'] = df.apply(lambda row: norm.normalize(row['Poem Body']), axis=1)

In [21]:
df_ii

Author Name                                      Title of Poem  \
0        khayyam        {رباعی شماره ۱۴۳: قومی متفکرند اندر ره دین}   
1        khayyam     {رباعی شماره ۱۵۹: از کوزه‌گری کوزه خریدم باری}   
2        khayyam   {رباعی شماره ۱۴: این بحر وجود آمده بیرون ز نهفت}   
3        khayyam        {رباعی شماره ۹۴: هم دانه امید به خرمن ماند}   
4        khayyam      {رباعی شماره ۲: چون عهده نمی‌شود کسی فردا را}   
...          ...                                                ...   
7876       hafez  {غزل شماره ۱۷۴: مژده ای دل که دگر باد صبا بازآمد}   
7877       hafez  {غزل شماره ۱۲۱: هر آن کو خاطر مجموع و یار نازن...   
7878       hafez         {غزل شماره ۴۳۷: ای قصه بهشت ز کویت حکایتی}   
7879       hafez   {غزل شماره ۲۷: در دیر مغان آمد یارم قدحی در دست}   
7880       hafez   {غزل شماره ۲۴۳: بوی خوش تو هر که ز باد صبا شنید}   

                                              Poem Body  \
0     قومی متفکرند اندر ره دین\n&&\nقومی به گمان فتا...   
1     از کوزه‌گری کوزه خریدم باری\n&&\nآن کوزه سخن گ...   
2     این بحر وجود آمده بیرون ز نهفت\n&&\nکس نیست که...   
3     هم دانه امید به خرمن ماند\n&&\nهم باغ و سرای ب...   
4     چون عهده نمی‌شود کسی فردا را\n&&\nحالی خوش دار...   
...                                                 ...   
7876  مژده ای دل که دگر باد صبا بازآمد\n&&\nهدهد خوش...   
7877  هر آن کو خاطر مجموع و یار نازنین دارد\n&&\nسعا...   
7878  ای قصه بهشت ز کویت حکایتی\n&&\nشرح جمال حور ز ...   
7879  در دیر مغان آمد یارم قدحی در دست\n&&\nمست از م...   
7880  بوی خوش تو هر که ز باد صبا شنید\n&&\nاز یار آش...   

                                        Nomralized Poem  
0     قومی متفکرند اندر ره دین\n&&\nقومی به گمان فتا...  
1     از کوزه‌گری کوزه خریدم باری\n&&\nآن کوزه سخن گ...  
2     این بحر وجود آمده بیرون ز نهفت\n&&\nکس نیست که...  
3     هم دانه امید به خرمن ماند\n&&\nهم باغ و سرای ب...  
4     چون عهده نمی‌شود کسی فردا را\n&&\nحالی خوش دار...  
...                                                 ...  
7876  مژده‌ای دل که دگر باد صبا بازآمد\n&&\nهدهد خوش...  
7877  هر آن کو خاطر مجموع و یار نازنین دارد\n&&\nسعا...  
7878  ای قصه بهشت ز کویت حکایتی\n&&\nشرح جمال حور ز ...  
7879  در دیر مغان آمد یارم قدحی در دست\n&&\nمست از م...  
7880  بوی خوش تو هر که ز باد صبا شنید\n&&\nاز یار آش...  

[7881 rows x 4 columns]

# Tokenizing

In [22]:
tokenizer = WordTokenizer()

In [23]:
df_ii['Tokenized_Poem'] = df.apply(lambda row: tokenizer.tokenize(row['Nomralized Poem']), axis=1)

In [24]:
res2 = [','.join(ele) for ele in df_ii['Tokenized_Poem']] 

In [25]:
csv_list2 = to_csv(p_author2, p_title ,res2)

In [26]:
df = pd.DataFrame(csv_list2,columns=['Author Name','Title of Poem','Poem Body'])

In [27]:
df

Author Name                                      Title of Poem  \
0        khayyam        {رباعی شماره ۱۴۳: قومی متفکرند اندر ره دین}   
1        khayyam     {رباعی شماره ۱۵۹: از کوزه‌گری کوزه خریدم باری}   
2        khayyam   {رباعی شماره ۱۴: این بحر وجود آمده بیرون ز نهفت}   
3        khayyam        {رباعی شماره ۹۴: هم دانه امید به خرمن ماند}   
4        khayyam      {رباعی شماره ۲: چون عهده نمی‌شود کسی فردا را}   
...          ...                                                ...   
7876       hafez  {غزل شماره ۱۷۴: مژده ای دل که دگر باد صبا بازآمد}   
7877       hafez  {غزل شماره ۱۲۱: هر آن کو خاطر مجموع و یار نازن...   
7878       hafez         {غزل شماره ۴۳۷: ای قصه بهشت ز کویت حکایتی}   
7879       hafez   {غزل شماره ۲۷: در دیر مغان آمد یارم قدحی در دست}   
7880       hafez   {غزل شماره ۲۴۳: بوی خوش تو هر که ز باد صبا شنید}   

                                              Poem Body  
0     قومی,متفکرند,اندر,ره,دین,&&,قومی,به,گمان,فتاده...  
1     از,کوزه‌گری,کوزه,خریدم,باری,&&,آن,کوزه,سخن,گفت...  
2     این,بحر,وجود,آمده,بیرون,ز,نهفت,&&,کس,نیست,که,ا...  
3     هم,دانه,امید,به,خرمن,ماند,&&,هم,باغ,و,سرای,بی,...  
4     چون,عهده,نمی‌شود,کسی,فردا,را,&&,حالی,خوش,دار,ا...  
...                                                 ...  
7876  مژده‌ای,دل,که,دگر,باد,صبا,بازآمد,&&,هدهد,خوش,خ...  
7877  هر,آن,کو,خاطر,مجموع,و,یار,نازنین,دارد,&&,سعادت...  
7878  ای,قصه,بهشت,ز,کویت,حکایتی,&&,شرح,جمال,حور,ز,رو...  
7879  در,دیر,مغان,آمد,یارم,قدحی,در,دست,&&,مست,از,می‌...  
7880  بوی,خوش,تو,هر,که,ز,باد,صبا,شنید,&&,از,یار,آشنا...  

[7881 rows x 3 columns]

# Stemming

### unfortunately the stemming system of hazm is not strong enough

# Remove Stop Words

In [32]:
def stop_word(file_name):
    with open(file_name, 'r', encoding="utf8") as myfile:
        stop_words = myfile.read().replace('\n', ' ').replace("\u200c","").replace("\ufeff","").replace("."," ").split(' ')# a list of stop words
    return stop_words
stop_words = stop_word('Stopwords')
print(stop_words)

['و', 'که', 'از', 'به', 'را', 'در', 'تو', 'ز', 'آن', 'بر', 'او', 'این', 'چو', 'چون', 'تا', 'ای', 'هر', 'با', 'چه', 'بود', 'شد', 'ما', 'سر', 'گر', 'نه', 'همه', 'خود', 'اندر', 'است', 'هم', 'کرد', 'آمد', 'پیش', 'نیست', 'کن', 'سوی', 'باشد', 'کند', 'اگر', 'چنین', 'شود', 'پر', 'پس', 'همی', 'کز', 'یا', 'کی', 'آید', 'دارد', 'مر', '']


In [28]:
def pers_alphab(line):
    """
    This function removes all the elements that are in a Persian
    literature that is not a part of a normal alphabet.    
    """
   
    # replacing all spaces,hyphens,  with white space
    space_pattern = r"[\xad\ufeff\u200e\u200d\u200b\x7f\u202a\u2003\xa0\u206e\u200c\x9d]"
    space_pattern = re.compile(space_pattern)
    line = space_pattern.sub(" ", line)
    
    letter_dict = dict()
    letter_dict[u"ۀ"] = u"ه"
    letter_dict[u"ة"] = u"ت"
    letter_dict[u"ي"] = u"ی"
    letter_dict[u"ؤ"] = u"و"
    letter_dict[u"إ"] = u"ا"
    letter_dict[u"ٹ"] = u"ت"
    letter_dict[u"ڈ"] = u"د"
    letter_dict[u"ئ"] = u"ی"
    letter_dict[u"ﻨ"] = u"ن"
    letter_dict[u"ﺠ"] = u"ج"
    letter_dict[u"ﻣ"] = u"م"
    letter_dict[u"ﷲ"] = u""
    letter_dict[u"ﻳ"] = u"ی"
    letter_dict[u"ٻ"] = u"ب"
    letter_dict[u"ٱ"] = u"ا"
    letter_dict[u"ڵ"] = u"ل"
    letter_dict[u"ﭘ"] = u"پ"
    letter_dict[u"ﻪ"] = u"ه"
    letter_dict[u"ﻳ"] = u"ی"
    letter_dict[u"ٻ"] = u"ب"
    letter_dict[u"ں"] = u"ن"
    letter_dict[u"ٶ"] = u"و"
    letter_dict[u"ٲ"] = u"ا"
    letter_dict[u"ہ"] = u"ه"
    letter_dict[u"ﻩ"] = u"ه"
    letter_dict[u"ﻩ"] = u"ه"
    letter_dict[u"ك"] = u"ک"
    letter_dict[u"ﺆ"] = u"و"
    letter_dict[u"أ"] = u"ا"
    letter_dict[u"ﺪ"] = u"د"
    
    # this function replace the keys of letter_dict with its values
    letter_pattern = re.compile(r"(" + "|".join(letter_dict.keys()) + r")")
    line = letter_pattern.sub(lambda x: letter_dict[x.group()], line) 
    
    
    return line

In [29]:
df_ii['Parsed'] = df.apply(lambda row: pers_alphab(row['Poem Body']), axis=1)

In [30]:
df_ii['Parsed']

0       قومی,متفکرند,اندر,ره,دین,&&,قومی,به,گمان,فتاده...
1       از,کوزه گری,کوزه,خریدم,باری,&&,آن,کوزه,سخن,گفت...
2       این,بحر,وجود,آمده,بیرون,ز,نهفت,&&,کس,نیست,که,ا...
3       هم,دانه,امید,به,خرمن,ماند,&&,هم,باغ,و,سرای,بی,...
4       چون,عهده,نمی شود,کسی,فردا,را,&&,حالی,خوش,دار,ا...
                              ...                        
7876    مژده ای,دل,که,دگر,باد,صبا,بازآمد,&&,هدهد,خوش,خ...
7877    هر,آن,کو,خاطر,مجموع,و,یار,نازنین,دارد,&&,سعادت...
7878    ای,قصه,بهشت,ز,کویت,حکایتی,&&,شرح,جمال,حور,ز,رو...
7879    در,دیر,مغان,آمد,یارم,قدحی,در,دست,&&,مست,از,می ...
7880    بوی,خوش,تو,هر,که,ز,باد,صبا,شنید,&&,از,یار,آشنا...
Name: Parsed, Length: 7881, dtype: object

In [33]:
pat = r'\b(?:{})\b'.format('|'.join(stop_words[:]))
df_ii['without_stopwords'] = df_ii['Parsed'].str.replace(pat, '')
df_ii['without_stopwords'] = df_ii['without_stopwords'].str.replace(r'\s+', ' ')

# Stemming 

In [36]:
df_ii['without_stopwords']

0       قومی,متفکرند,,ره,دین,&&,قومی,,گمان,فتاده,,راه,...
1       ,کوزه گری,کوزه,خریدم,باری,&&,,کوزه,سخن,گفت,,,ا...
2       ,بحر,وجود,آمده,بیرون,,نهفت,&&,کس,,,,گوهر,تحقیق...
3       ,دانه,امید,,خرمن,ماند,&&,,باغ,,سرای,بی,,,من,ما...
4       ,عهده,نمی ,کسی,فردا,,&&,حالی,خوش,دار,,دل,,سودا...
                              ...                        
7876    مژده ,دل,,دگر,باد,صبا,بازآمد,&&,هدهد,خوش,خبر,,...
7877    ,,کو,خاطر,مجموع,,یار,نازنین,,&&,سعادت,همدم,,گش...
7878    ,قصه,بهشت,,کویت,حکایتی,&&,شرح,جمال,حور,,رویت,ر...
7879    ,دیر,مغان,,یارم,قدحی,,دست,&&,مست,,می ,میخواران...
7880    بوی,خوش,,,,,باد,صبا,شنید,&&,,یار,آشنا,سخن,آشنا...
Name: without_stopwords, Length: 7881, dtype: object

In [37]:
to_drop = ['Parsed','Tokenized_Poem','Nomralized Poem','Poem Body']

In [38]:
df = df_ii

In [39]:
df = df.drop(to_drop, axis = 1)

In [40]:
df

Author Name                                      Title of Poem  \
0        khayyam        {رباعی شماره ۱۴۳: قومی متفکرند اندر ره دین}   
1        khayyam     {رباعی شماره ۱۵۹: از کوزه‌گری کوزه خریدم باری}   
2        khayyam   {رباعی شماره ۱۴: این بحر وجود آمده بیرون ز نهفت}   
3        khayyam        {رباعی شماره ۹۴: هم دانه امید به خرمن ماند}   
4        khayyam      {رباعی شماره ۲: چون عهده نمی‌شود کسی فردا را}   
...          ...                                                ...   
7876       hafez  {غزل شماره ۱۷۴: مژده ای دل که دگر باد صبا بازآمد}   
7877       hafez  {غزل شماره ۱۲۱: هر آن کو خاطر مجموع و یار نازن...   
7878       hafez         {غزل شماره ۴۳۷: ای قصه بهشت ز کویت حکایتی}   
7879       hafez   {غزل شماره ۲۷: در دیر مغان آمد یارم قدحی در دست}   
7880       hafez   {غزل شماره ۲۴۳: بوی خوش تو هر که ز باد صبا شنید}   

                                      without_stopwords  
0     قومی,متفکرند,,ره,دین,&&,قومی,,گمان,فتاده,,راه,...  
1     ,کوزه گری,کوزه,خریدم,باری,&&,,کوزه,سخن,گفت,,,ا...  
2     ,بحر,وجود,آمده,بیرون,,نهفت,&&,کس,,,,گوهر,تحقیق...  
3     ,دانه,امید,,خرمن,ماند,&&,,باغ,,سرای,بی,,,من,ما...  
4     ,عهده,نمی ,کسی,فردا,,&&,حالی,خوش,دار,,دل,,سودا...  
...                                                 ...  
7876  مژده ,دل,,دگر,باد,صبا,بازآمد,&&,هدهد,خوش,خبر,,...  
7877  ,,کو,خاطر,مجموع,,یار,نازنین,,&&,سعادت,همدم,,گش...  
7878  ,قصه,بهشت,,کویت,حکایتی,&&,شرح,جمال,حور,,رویت,ر...  
7879  ,دیر,مغان,,یارم,قدحی,,دست,&&,مست,,می ,میخواران...  
7880  بوی,خوش,,,,,باد,صبا,شنید,&&,,یار,آشنا,سخن,آشنا...  

[7881 rows x 3 columns]

In [32]:
to_drop = ['Poem Body','Nomralized Poem','Tokenized_Poem','Parsed']
df  = df.drop(to_drop ,axis =1)

In [41]:
df.columns = ['Shaer', 'Title', 'Poem']

In [42]:
df.head()

Shaer                                             Title  \
0  khayyam       {رباعی شماره ۱۴۳: قومی متفکرند اندر ره دین}   
1  khayyam    {رباعی شماره ۱۵۹: از کوزه‌گری کوزه خریدم باری}   
2  khayyam  {رباعی شماره ۱۴: این بحر وجود آمده بیرون ز نهفت}   
3  khayyam       {رباعی شماره ۹۴: هم دانه امید به خرمن ماند}   
4  khayyam     {رباعی شماره ۲: چون عهده نمی‌شود کسی فردا را}   

                                                Poem  
0  قومی,متفکرند,,ره,دین,&&,قومی,,گمان,فتاده,,راه,...  
1  ,کوزه گری,کوزه,خریدم,باری,&&,,کوزه,سخن,گفت,,,ا...  
2  ,بحر,وجود,آمده,بیرون,,نهفت,&&,کس,,,,گوهر,تحقیق...  
3  ,دانه,امید,,خرمن,ماند,&&,,باغ,,سرای,بی,,,من,ما...  
4  ,عهده,نمی ,کسی,فردا,,&&,حالی,خوش,دار,,دل,,سودا...

# whoosh Part ( schema , indexing , querying ) 

In [47]:
###################################################################################
#whoosh
from whoosh import fields , index
from whoosh import qparser
from whoosh.fields import Schema, TEXT, ID, STORED
from whoosh.analysis import StemmingAnalyzer,StandardAnalyzer
from whoosh import index
import os, os.path
from whoosh.qparser import QueryParser
from whoosh.qparser import FuzzyTermPlugin
from whoosh.index import open_dir
import codecs

In [48]:
#Building schema for whoosh

In [49]:
schema = Schema(author=TEXT(stored=True),
                title=TEXT(stored=True),
                body=TEXT(stored=True))

In [50]:
##indexing on whoosh

In [51]:
def populate_index(dirname, dataframe, schema):
    # Checks for existing index path and creates one if not present
    if not os.path.exists(dirname):
        os.mkdir(dirname)
    print("Creating the Index")
    ix = index.create_in(dirname, schema)
    with ix.writer() as writer:
        # Imports stories from pandas df
        print("Populating the Index")
        for i in dataframe.index:
            add_stories(i, dataframe, writer)

In [52]:
def add_stories(i, dataframe, writer):   
   
    writer.update_document(author = str(dataframe.loc[i, 'Shaer']),
                           title = str(dataframe.loc[i, 'Title']),
                           body = str(dataframe.loc[i,'Poem']))
    

In [53]:
populate_index('Poem_Index', df, schema)

Creating the Index
Populating the Index


In [46]:
#Query searcher whoosh

In [54]:
def index_search(dirname, search_fields, search_query):
    ix = index.open_dir(dirname)
    schema = ix.schema
    print(ix)
    print(schema)
    # Create query parser that looks through designated fields in index
    og = qparser.OrGroup.factory()
    mp = qparser.MultifieldParser(search_fields, schema, group = og)

    # This is the user query
    q = mp.parse(search_query)
    

    # Actual searcher, prints top 10 hits
    with ix.searcher() as s:
        results = s.search(q, limit = 10)
        parser = QueryParser("content", schema=ix.schema)

       
        print("Search Results: ")
        print(results)
      

In [55]:
index_search('Poem_Index', ['Title', 'Poem'], u"بردن پادشاه آن طبیب را بر بیمار تا حال او را ببیند خلوت طلبیدن آن ولی از پادشاه جهت دریافتن رنج کنیزک بردن پادشاه آن طبیب را بر بیمار تا حال او را ببیند ملاقات پادشاه با آن ولی که در خوابش نمودند ظاهر شدن عجز حکیمان از معالجهٔ کنیزک و روی آوردن پادشاه به درگاه اله و در خواب دیدن او ولیی راعاشق شدن پادشاه بر کنیزک رنجور و تدبیر کردن در صحت او")

FileIndex(FileStorage('Poem_Index'), 'MAIN')
<Schema: ['author', 'body', 'title']>
Search Results: 
<Top 0 Results for Or([Term('Title', 'بردن'), Term('Poem', 'بردن'), Term('Title', 'پادشاه'), Term('Poem', 'پادشاه'), Term('Title', 'آن'), Term('Poem', 'آن'), Term('Title', 'طبیب'), Term('Poem', 'طبیب'), Term('Title', 'را'), Term('Poem', 'را'), Term('Title', 'بر'), Term('Poem', 'بر'), Term('Title', 'بیمار'), Term('Poem', 'بیمار'), Term('Title', 'تا'), Term('Poem', 'تا'), Term('Title', 'حال'), Term('Poem', 'حال'), Term('Title', 'او'), Term('Poem', 'او'), Term('Title', 'ببیند'), Term('Poem', 'ببیند'), Term('Title', 'خلوت'), Term('Poem', 'خلوت'), Term('Title', 'طلبیدن'), Term('Poem', 'طلبیدن'), Term('Title', 'ولی'), Term('Poem', 'ولی'), Term('Title', 'از'), Term('Poem', 'از'), Term('Title', 'جهت'), Term('Poem', 'جهت'), Term('Title', 'دریافتن'), Term('Poem', 'دریافتن'), Term('Title', 'رنج'), Term('Poem', 'رنج'), Term('Title', 'کنیزک'), Term('Poem', 'کنیزک'), Term('Title', 'ملاقات'), Term('Poe

Whoosh is not working for persian docs -- Just like Pylucene

# Building Inverted Index and TF-IDF

In [56]:
from collections import defaultdict
#My module
inv_indx = defaultdict(list)
for idx, text in enumerate(df_ii['Tokenized_Poem']):
    for word in text:
        inv_indx[word].append(idx)

In [58]:
#inv_indx

In [59]:
#sklearn module
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
v = TfidfVectorizer()
x = v.fit_transform(df['Poem'])

In [60]:
%%time
x.toarray()

CPU times: user 343 ms, sys: 584 ms, total: 928 ms
Wall time: 925 ms


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.04953164, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [61]:
x.shape

(7881, 48938)

In [62]:
v.vocabulary_

{'قومی': 32141,
 'متفکرند': 33493,
 'ره': 21546,
 'دین': 20343,
 'گمان': 47807,
 'فتاده': 30036,
 'راه': 20786,
 'یقین': 48694,
 'میترسم': 37287,
 'بانگ': 6540,
 'روزی': 21789,
 'کای': 45653,
 'بیخبران': 11383,
 'آنست': 668,
 'کوزه': 46785,
 'گری': 47389,
 'خریدم': 16546,
 'باری': 5874,
 'سخن': 23580,
 'گفت': 47612,
 'اسراری': 2091,
 'شاهی': 25247,
 'بودم': 10443,
 'جام': 13805,
 'زرینم': 22443,
 'اکنون': 5465,
 'شده': 25462,
 'ام': 4470,
 'خماری': 16974,
 'بحر': 7012,
 'وجود': 42572,
 'آمده': 571,
 'بیرون': 11473,
 'نهفت': 40287,
 'کس': 46034,
 'گوهر': 48052,
 'تحقیق': 12145,
 'بسفت': 8959,
 'سخنی': 23608,
 'سودا': 24543,
 'گفتند': 47635,
 'زآن': 22080,
 'روی': 21901,
 'هست': 41587,
 'نمی': 40090,
 'داند': 18311,
 'دانه': 18355,
 'امید': 4628,
 'خرمن': 16455,
 'ماند': 33224,
 'باغ': 6234,
 'سرای': 23677,
 'بی': 11222,
 'من': 36258,
 'سیم': 25000,
 'زر': 22345,
 'خویش': 17992,
 'درمی': 18970,
 'بجوی': 6991,
 'دوست': 20081,
 'بخور': 7290,
 'بدشمن': 7515,
 'عهده': 29058,
 'کسی': 46080,
 

In [63]:
v.get_feature_names()

['آب',
 'آبا',
 'آباد',
 'آبادان',
 'آبادست',
 'آبادم',
 'آبادی',
 'آباقان',
 'آبان',
 'آبت',
 'آبتان',
 'آبحیات',
 'آبخوار',
 'آبخواره',
 'آبخور',
 'آبخورد',
 'آبدار',
 'آبدارست',
 'آبدارش',
 'آبداری',
 'آبدان',
 'آبدست',
 'آبدستم',
 'آبرو',
 'آبروی',
 'آبرویش',
 'آبرویم',
 'آبرویی',
 'آبریز',
 'آبست',
 'آبستان',
 'آبستست',
 'آبستن',
 'آبستنان',
 'آبستنست',
 'آبستنیم',
 'آبستی',
 'آبش',
 'آبشان',
 'آبلستان',
 'آبله',
 'آبم',
 'آبمی',
 'آبناک',
 'آبند',
 'آبنوس',
 'آبنوسی',
 'آبها',
 'آبهاست',
 'آبهای',
 'آبکش',
 'آبگون',
 'آبگونم',
 'آبگونی',
 'آبگیر',
 'آبگیرست',
 'آبگیری',
 'آبگینست',
 'آبگینه',
 'آبی',
 'آبیست',
 'آبیش',
 'آبیم',
 'آبیه',
 'آبیی',
 'آت',
 'آتاکم',
 'آتش',
 'آتشان',
 'آتشبار',
 'آتشت',
 'آتشتان',
 'آتشخوار',
 'آتشخواره',
 'آتشخوارگانش',
 'آتشدان',
 'آتشروی',
 'آتشرویی',
 'آتشست',
 'آتشش',
 'آتششان',
 'آتشم',
 'آتشناک',
 'آتشند',
 'آتشها',
 'آتشهای',
 'آتشکدست',
 'آتشکده',
 'آتشگون',
 'آتشی',
 'آتشیت',
 'آتشیست',
 'آتشیم',
 'آتشین',
 'آتشینا',
 'آتشینت',
 'آتشینش',
 

Query Processing

In [65]:
def query_Searcher(query):
    query_vec = v.transform([query]) 
    results = cosine_similarity(x,query_vec).reshape((-1,))
    for i in results.argsort()[-10:][::-1]:
        print(df.iloc[i,0],"--",df.iloc[i,1])
    

In [66]:
query1 = "دادن پدر لیلی را به ابن سلام آگاهی مجنون از شوهر کردن لیلی رفتن پدر مجنون به دیدن فرزند وداع کردن پدر مجنون را آگاهی مجنون از مرگ پدر انس مجنون با وحوش و سباع نیایش کردن مجنون به درگاه خدای تعالی رسیدن نامه لیلی به مجنون نامه مجنون در پاسخ لیلی آمدن سلیم عامری خال مجنون به دیدن او دیدن مادر مجنون را آگاهی مجنون از وفات مادر خواندن لیلی مجنون را غزل خواندن مجنون نزد لیلی آشنا شدن سلام بغدادی با مجنون وفات یافتن ابن سلام شوهر لیلی صفت رسیدن خزان و در گذشتن لیلی وفات مجنون بر روضه لیلی"

In [68]:
query2 = "بیان آنک کشتن و زهر دادن مرد زرگر به اشارت الهی بود نه به هوای نفس و تامل فاسد فرستادن پادشاه رسولان به سمرقند به آوردن زرگر"

In [72]:
query3 = "حکایت آن زن کی گفت شوهر را کی گوشت را گربه خورد شوهر گربه را به ترازو بر کشید گربه نیم من برآمد گفت ای زن گوشت نیم من بود و افزون اگر این گوشتست گربه کو و اگر این گربه است گوشت کو"

In [69]:
query_Searcher(query1)

moulavi -- {غزل شماره ۱۴۵۶: توبه نکنم هرگز زین جرم که من دارم}
moulavi -- {غزل شماره ۳۱۲۰: اگر چه لطیفی و زیبالقایی}
moulavi -- {رباعی شماره ۱۴۸۳: سرمست توام نه از می و نز افیون}
saadi -- {رباعی شماره ۱: هر ساعتم اندرون بجوشد خون را}
saadi -- {رباعی شماره ۶۳: مجنون اگر احتمال لیلی نکند}
moulavi -- {بخش ۵۸ - چالیش عقل با نفس هم چون تنازع  مجنون با ناقه میل مجنون  سوی حره میل ناقه واپس سوی کره  چنانک گفت مجنون هوا ناقتی خلفی و قدامی الهوی  و انی و ایاها لمختلفان}
moulavi -- {غزل شماره ۱۸۵۴: چه دانی تو خراباتی که هست از شش جهت بیرون}
saadi -- {غزل ۴۷۴: نشان بخت بلندست و طالع میمون}
moulavi -- {بخش ۷۹ - بیان اتحاد عاشق و معشوق از روی حقیقت اگر چه متضادند  از روی آنک نیاز ضد بی‌نیازیست چنان که آینه بی‌صورتست و  ساده است و بی‌صورتی ضد صورتست ولکن میان ایشان اتحادیست  در حقیقت کی شرح آن درازست و العاقل یکفیه الاشاره}
moulavi -- {غزل شماره ۲۴۵: از برای صلاح مجنون را}


In [70]:
query_Searcher(query2)

saadi -- {رباعی شماره ۱۱۸: مه را ز فلک به طرف بام آوردن}
moulavi -- {بخش ۸ - دریافتن آن ولی رنج را و عرض کردن رنج او را پیش پادشاه}
moulavi -- {رباعی شماره ۱۹۰۵: عشقت صنما چه دلبریها کردی}
moulavi -- {غزل شماره ۵۲: چون همه عشق روی تست جمله رضای نفس ما}
moulavi -- {غزل شماره ۱۲۸۳: ندا رسید به عاشق ز عالم رازش}
moulavi -- {رباعی شماره ۴۷۵: آن را منگر که ذوفنون آید مرد}
saadi -- {بخش ۲ - گفتار اندر فضیلت خاموشی: اگر پای در دامن آری چو کوه}
saadi -- {غزل ۴۶۳: چه خوش بود دو دلارام دست در گردن}
moulavi -- {بخش ۱۶۳ - حکایت آن مجاهد کی از همیان سیم هر روز یک درم در خندق انداختی به تفاریق از بهر ستیزهٔ حرص و آرزوی نفس و وسوسهٔ نفس کی چون می‌اندازی به خندق باری به یک‌بار بینداز تا خلاص یابم کی الیاس احدی الراحتین او گفته کی این راحت نیز ندهم}
moulavi -- {غزل شماره ۲۸۸۳: چه حریصی که مرا بی‌خور و بی‌خواب کنی}


In [73]:
query_Searcher(query3)

moulavi -- {بخش ۱۴۴ - حکایت آن زن کی گفت شوهر را کی گوشت را گربه خورد شوهر گربه را به ترازو بر کشید گربه نیم من برآمد گفت ای زن گوشت نیم من بود و افزون اگر این گوشتست گربه کو و اگر این گربه است گوشت کو}
moulavi -- {غزل شماره ۸۱۳: موشکی صندوق را سوراخ کرد}
moulavi -- {غزل شماره ۷۵۰: شاد شد جانم که چشمت وعده احسان نهاد}
moulavi -- {غزل شماره ۲۲۲۶: ای بکرده رخت عشاقان گرو}
moulavi -- {بخش ۷۵ - قصهٔ آنک کسی به کسی مشورت می‌کرد گفتش  مشورت با دیگری کن کی من عدوی توم}
moulavi -- {بخش ۱۳۳ - حکایت آن زن پلیدکار کی شوهر را گفت کی آن خیالات از سر امرودبن می‌نماید ترا کی چنینها نماید چشم آدمی را سر آن امرودبن از سر امرودبن فرود آی تا آن خیالها برود و اگر کسی گوید کی آنچ آن مرد  می‌دید خیال نبود و جواب این مثالیست نه مثل در مثال همین  قدر بس بود کی اگر بر سر امرودبن نرفتی هرگز آنها ندیدی خواه خیال خواه حقیقت}
moulavi -- {بخش ۲۱ - آمن بودن بلعم باعور کی امتحانها کرد حضرت او را و از آنها روی سپید آمده بود}
moulavi -- {رباعی شماره ۱۰۹۷: در عشق نوا جزو زند آنگه کل}
moulavi -- {غزل شماره ۱۶۵۶: هم به در

################################################################################################################ 

# ----------------------------------------------PART 2-----------------------------------------------------

In [74]:

#Todo List: 1- Build a module for evaluation(accuracy-precision-recall-fscore)
           #2- Build a module for KNN and Naive Bayes 
           #3- Build SVM module
           

In [75]:
path2 = "/home/yazdan/Documents/IR Project/PersianPoemsData/Poems"


In [76]:
poems = {}
key = 0
for (dir_path,dir_name,file_names) in os.walk(path2):
    for the_file in file_names:
        with open(dir_path + '/' + the_file, 'r',encoding="utf-8") as f:
            filled = f.readlines()
            poems[int(key)] = filled
            key = key+1
    print (poems.get(4))

['رفتم به طبیب جان گفتم که ببین دستم\n', 'هم بی\u200cدل و بیمارم هم عاشق و سرمستم\n', 'صد گونه خلل دارم ای کاش یکی بودی\n', 'با این همه علت\u200cها در شنقصه پیوستم\n', 'گفتا که نه تو مردی گفتم که بلی اما\n', 'چون بوی توام آمد از گور برون جستم\n', 'آن صورت روحانی وان مشرق یزدانی\n', 'وان یوسف کنعانی کز وی کف خود خستم\n', 'خوش خوش سوی من آمد دستی به دلم برزد\n', 'گفتا ز چه دستی تو گفتم که از این دستم\n', 'چون عربده می کردم درداد می و خوردم\n', 'افروخت رخ زردم وز عربده وارستم\n', 'پس جامه برون کردم مستانه جنون کردم\n', 'در حلقه آن مستان در میمنه بنشستم\n', 'صد جام بنوشیدم صد گونه بجوشیدم\n', 'صد کاسه بریزیدم صد کوزه دراشکستم\n', 'گوساله زرین را آن قوم پرستیده\n', 'گوساله گرگینم گر عشق بنپرستم\n', 'بازم شه روحانی می خواند پنهانی\n', 'بر می کشدم بالا شاهانه از این پستم\n', 'پابست توام جانا سرمست توام جانا\n', 'در دست توام جانا گر تیرم وگر شستم\n', 'چست توام ار چستم مست توام ار مستم\n', 'پست توام ار پستم هست توام ار هستم\n', 'در چرخ درآوردی چون مست خودم کردی\n', 'چون تو سر خم بستی من نیز دها

In [77]:
df3 = pd.DataFrame(poems.items(), columns=['ID', 'Poem'])

In [78]:
df3.head()

ID                                               Poem
0   0  [من جان تو نیستم مگو جان غلطی\n, من جان جنیدم ...
1   1  [بود بازرگان و او را طوطیی\n, در قفس محبوس زیب...
2   2  [دی مست بدی دلا و چست و سفری\n, امروز چه خورده...
3   3  [طوبی لمن آواه سر فؤاده\n, سکن الفؤاد بعشقه و ...
4   4  [رفتم به طبیب جان گفتم که ببین دستم\n, هم بی‌د...

In [79]:
res3 = [''.join(ele) for ele in df3['Poem']] 

print(str(res3[4]))

رفتم به طبیب جان گفتم که ببین دستم
هم بی‌دل و بیمارم هم عاشق و سرمستم
صد گونه خلل دارم ای کاش یکی بودی
با این همه علت‌ها در شنقصه پیوستم
گفتا که نه تو مردی گفتم که بلی اما
چون بوی توام آمد از گور برون جستم
آن صورت روحانی وان مشرق یزدانی
وان یوسف کنعانی کز وی کف خود خستم
خوش خوش سوی من آمد دستی به دلم برزد
گفتا ز چه دستی تو گفتم که از این دستم
چون عربده می کردم درداد می و خوردم
افروخت رخ زردم وز عربده وارستم
پس جامه برون کردم مستانه جنون کردم
در حلقه آن مستان در میمنه بنشستم
صد جام بنوشیدم صد گونه بجوشیدم
صد کاسه بریزیدم صد کوزه دراشکستم
گوساله زرین را آن قوم پرستیده
گوساله گرگینم گر عشق بنپرستم
بازم شه روحانی می خواند پنهانی
بر می کشدم بالا شاهانه از این پستم
پابست توام جانا سرمست توام جانا
در دست توام جانا گر تیرم وگر شستم
چست توام ار چستم مست توام ار مستم
پست توام ار پستم هست توام ار هستم
در چرخ درآوردی چون مست خودم کردی
چون تو سر خم بستی من نیز دهان بستم



# KNN 

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [86]:
X = x.toarray()

In [87]:
df['Shaer'].unique()

array(['khayyam', 'moulavi', 'saadi', 'hafez'], dtype=object)

In [88]:
class_to_num = {'khayyam': 0,
                  'moulavi': 1,
                  'saadi': 2,
                  'hafez': 3}
df['tmp'] = df['Shaer'].map(class_to_num)
y = df['tmp']

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [69]:
%%time

clf = KNeighborsClassifier(n_neighbors=3,n_jobs=-1)
clf.fit(X_train, y_train)

CPU times: user 29.8 s, sys: 122 ms, total: 29.9 s
Wall time: 29.9 s


In [70]:
%%time
y_pred = clf.predict(X_test)

CPU times: user 1h 2min 36s, sys: 1.08 s, total: 1h 2min 37s
Wall time: 7min 56s


In [74]:
print(" The evaluated scores for knn with 3 neighbours is:")
print("---------------------------------------------------")
#print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

 The evaluated scores for knn with 3 neighbours is:
---------------------------------------------------
              precision    recall  f1-score   support

           0       0.29      0.21      0.24        48
           1       0.85      0.96      0.90      1868
           2       0.66      0.36      0.46       311
           3       0.36      0.15      0.21       138

    accuracy                           0.82      2365
   macro avg       0.54      0.42      0.45      2365
weighted avg       0.79      0.82      0.79      2365



In [75]:
%%time

clf2 = KNeighborsClassifier(n_neighbors=5,n_jobs=-1)
clf2.fit(X_train, y_train)

CPU times: user 30.8 s, sys: 108 ms, total: 30.9 s
Wall time: 30.8 s


In [76]:
%%time
y_pred2 = clf2.predict(X_test)

CPU times: user 1h 3min 30s, sys: 772 ms, total: 1h 3min 30s
Wall time: 8min 4s


In [77]:
print(" The evaluated scores for knn with 5 neighbours is:")
print("---------------------------------------------------")
#print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred2))

 The evaluated scores for knn with 5 neighbours is:
---------------------------------------------------
              precision    recall  f1-score   support

           0       0.47      0.15      0.22        48
           1       0.84      0.98      0.91      1868
           2       0.72      0.33      0.46       311
           3       0.59      0.12      0.19       138

    accuracy                           0.83      2365
   macro avg       0.65      0.39      0.45      2365
weighted avg       0.80      0.83      0.79      2365



In [78]:
%%time

clf3 = KNeighborsClassifier(n_neighbors=1,n_jobs=-1)
clf3.fit(X_train, y_train)

CPU times: user 31 s, sys: 60 ms, total: 31 s
Wall time: 31 s


In [79]:
%%time
y_pred3 = clf3.predict(X_test)

CPU times: user 1h 56s, sys: 756 ms, total: 1h 57s
Wall time: 8min 7s


In [80]:
print(" The evaluated scores for knn with 1 neighbour is:")
print("---------------------------------------------------")
#print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred3))

 The evaluated scores for knn with 1 neighbour is:
---------------------------------------------------
              precision    recall  f1-score   support

           0       0.27      0.21      0.24        48
           1       0.86      0.88      0.87      1868
           2       0.46      0.38      0.41       311
           3       0.26      0.30      0.28       138

    accuracy                           0.77      2365
   macro avg       0.46      0.44      0.45      2365
weighted avg       0.76      0.77      0.77      2365



# /////////////////////////////////////////////////NAIVE BAYES//////////////////////////////////////////////////////////

In [90]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [45]:
gnb = GaussianNB()

In [46]:
gnb.fit(X_train, y_train)

GaussianNB()

In [47]:
GaussianNB(priors=None)

GaussianNB()

In [48]:
gnb.score(X_train, y_train)

0.9728063814358231

In [50]:
mnb = MultinomialNB(class_prior=None)

In [51]:
mnb.fit(X_train,y_train)

MultinomialNB()

In [58]:
y_pred = mnb.predict(X_test)

In [59]:
y_pred2 = gnb.predict(X_test)

In [64]:
print(" The evaluated scores for Multi- NB  is:")
print("---------------------------------------------------")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

 The evaluated scores for Multi- NB  is:
---------------------------------------------------
[[   0   53    0    0]
 [   0 1846    0    0]
 [   0  301    0    0]
 [   0  165    0    0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        53
           1       0.78      1.00      0.88      1846
           2       0.00      0.00      0.00       301
           3       0.00      0.00      0.00       165

    accuracy                           0.78      2365
   macro avg       0.20      0.25      0.22      2365
weighted avg       0.61      0.78      0.68      2365



In [63]:
print(" The evaluated scores for NB  is:")
print("---------------------------------------------------")
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

 The evaluated scores for NB  is:
---------------------------------------------------
[[   0   42    7    4]
 [   3 1708  109   26]
 [   0  183  116    2]
 [   0  135   19   11]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        53
           1       0.83      0.93      0.87      1846
           2       0.46      0.39      0.42       301
           3       0.26      0.07      0.11       165

    accuracy                           0.78      2365
   macro avg       0.39      0.34      0.35      2365
weighted avg       0.72      0.78      0.74      2365



# /////////////////////////////////////////////////////--*SVM*--///////////////////////////////////////////////////////////

In [65]:
from sklearn import svm

In [66]:
clf = svm.SVC(kernel='linear')

In [67]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [68]:
%%time
y_pred = clf.predict(X_test)

CPU times: user 9min 4s, sys: 76 ms, total: 9min 4s
Wall time: 9min 4s


In [69]:
print(" The evaluated scores for SVM Linear kernel is:")
print("---------------------------------------------------")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

 The evaluated scores for SVM Linear kernel is:
---------------------------------------------------
[[   4   49    0    0]
 [   0 1846    0    0]
 [   0   77  224    0]
 [   0   11    3  151]]
              precision    recall  f1-score   support

           0       1.00      0.08      0.14        53
           1       0.93      1.00      0.96      1846
           2       0.99      0.74      0.85       301
           3       1.00      0.92      0.96       165

    accuracy                           0.94      2365
   macro avg       0.98      0.68      0.73      2365
weighted avg       0.94      0.94      0.93      2365



In [70]:
clf2 = svm.SVC(kernel = 'rbf')

In [71]:
clf2.fit(X_train, y_train)

SVC()

In [74]:
%%time
y_pred2= clf2.predict(X_test)

CPU times: user 13min 23s, sys: 8.04 ms, total: 13min 23s
Wall time: 13min 23s


In [75]:
print(" The evaluated scores for SVM rbf kernel Mode is:")
print("---------------------------------------------------")
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

 The evaluated scores for SVM rbf kernel Mode is:
---------------------------------------------------
[[   0   53    0    0]
 [   0 1846    0    0]
 [   0  109  192    0]
 [   0   93    5   67]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        53
           1       0.88      1.00      0.94      1846
           2       0.97      0.64      0.77       301
           3       1.00      0.41      0.58       165

    accuracy                           0.89      2365
   macro avg       0.71      0.51      0.57      2365
weighted avg       0.88      0.89      0.87      2365



/home/yazdan/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
